### ISSUE TITLE
!ping command

### ISSUE THREAD

**Issue by Matthewrbowker** [DatGuy1/Filter-reporter#3]
To ensure the bot is up and listening, add a ping command that allows one to ping the bot and have it respond with "pong."

Example from wm-bot:

> 11:00:30 <Matthew_> !ping
> 11:00:31 <+wm-bot> Pong.

**Comment by DatGuy1** [comment]
I've added some code for it. Requesting Samtar to debug it.

**Comment by theresnotime** [comment]
zbot's core doesn't have anything pre-built for listening to the channel, but your ( @DatGuy1 ) code seems reasonable. Currently not working but I'll take a look tonight
